#!/bin/bash

## Mod's service management
##
## Copyright (C) 2025, Alexander K <https://github.com/drA1ex>
##
## This file may be distributed under the terms of the GNU GPLv3 license

# shellcheck disable=SC1091
source /opt/config/mod/.shell/common.sh


set -x

SKIP_REBOOT_F="/tmp/mod_skip_reboot"

message() {
    local text="$1"
    local prefix="${2:-"info"}"
    
    echo "RESPOND PREFIX='$prefix' MSG='$text'" > /tmp/printer
}

command() {
    local value="$1"
    
    echo "RESPOND TYPE=command MSG='$value'" > /tmp/printer
}

restart() {
    echo "Received restart signal."
    
    # Mount rootfs
    mkdir -p /_root
    mount "$ROOT_PART" /_root
    
    # Make sure boot scripts at it's place
    rm -f /_root/etc/init.d/S00fix
    ln -s /opt/config/mod/.shell/S00init /_root/etc/init.d/S00init
    
    umount /_root
    
    if [ -f "$SKIP_REBOOT_F" ]; then
        echo "Skip reboot because of skip flag."
        exit 0
    fi
    
    sync
    echo "REBOOT" > /tmp/printer
}

case "$1" in
    verify)
        GIT_BRANCH=$(git --git-dir=/opt/config/mod/.git rev-parse --abbrev-ref HEAD)
        VERSION="$(cat /opt/config/mod/version.txt)"
        NEW_VERSION=$(curl --location 'https://api.github.com/repos/dra1ex/ff5m/contents/version.txt?ref='"$GIT_BRANCH" \
             --header 'Accept: application/vnd.github.raw+json')
        
        if [ -z "$NEW_VERSION" ]; then
            echo "Unable to get the new version"
            exit 1
        fi
        
        if [ "${VERSION%.*}" != "${NEW_VERSION%.*}" ]; then
            message "This version cannot be updated via OTA." "!!"
            message "Insert a FAT32 USB drive and run DOWNLOAD_FIRMWARE_UPDATE, or download the latest firmware image manually from the Releases page." "!!"
            message "Visit: https://github.com/DrA1ex/ff5m/releases" "!!"

            command "action:prompt_end"
            command "action:prompt_begin OTA Update"
            command "action:prompt_text This version cannot be updated via OTA."
            command "action:prompt_text Insert a FAT32 USB drive and run DOWNLOAD_FIRMWARE_UPDATE, or download the latest firmware image manually."
            command "action:prompt_text https://github.com/DrA1ex/ff5m/releases"
            command "action:prompt_footer_button Download to USB|DOWNLOAD_FIRMWARE_UPDATE|primary"
            command "action:prompt_footer_button Close|RESPOND TYPE=command MSG=action:prompt_end|secondary"
            command "action:prompt_show"

            exit 1
            
            exit 1
        fi
    ;;
    restart)
        mv "$LOG_DIR/service.log.1" "$LOG_DIR/service.log.2" &> /dev/null
        mv "$LOG_DIR/service.log" "$LOG_DIR/service.log.1" &> /dev/null
        restart 2>&1 | tee "$LOG_DIR/service.log"
    ;;
    *)
        echo "Usage: $0 (restart)}"
        exit 1
esac
