#!/bin/sh
#
# Starts touchscreen uinput support.
#
# Copyright (C) 2025-2026, Alexander K <https://github.com/drA1ex>
#
# This file may be distributed under the terms of the GNU GPLv3 license
#

mkdir -p /var/run/

BIN=/usr/bin/ts_uinput
PIDFILE=/var/run/ts_uinput.pid
NICENESS=9

# variables must be present or ts_uinput will fail.

export TSLIB_TSDEVICE=/dev/input/event0
export TSLIB_PLUGINDIR=/usr/lib/ts
export TSLIB_CONFFILE=/etc/ts.conf
export TSLIB_CALIBFILE=/etc/pointercal
export TSLIB_FBDEVICE=/dev/fb0

create_link() {
    DEVICE=$(grep -l "ts_uinput" /sys/class/input/event*/device/name | head -n 1)
    if [ "$DEVICE" = "" ]; then
        echo "Unable to obtain input device."
        return 1
    fi

    DEVICE=${DEVICE%/device/name}
    DEVICE="/dev/input/${DEVICE##*/}"

    ln -fns "$DEVICE" /dev/input/guppy
}

start() {
    echo "Starting tslib uinput interface..."

    if [ -f "$PIDFILE" ] && kill -0 "$(cat "$PIDFILE")" 2>/dev/null; then
        create_link
        echo "Already running"
        return 0
    fi
    
    # First start
    if ! lsmod | grep -q uinput; then
        insmod /lib/modules/5.4.61/uinput.ko
        
        mkdir -p /tmp/parent_root
        mount /dev/mmcblk0p6 /tmp/parent_root
        
        ln -fns /tmp/parent_root/opt/tslib-1.12/etc/ts.conf /etc/
        ln -fns /tmp/parent_root/opt/tslib-1.12/etc/pointercal /etc/
    fi
    
    start-stop-daemon -S -q -b -m -p $PIDFILE -N $NICENESS --exec $BIN
    [ $? = 0 ] && sleep 3 && create_link && echo "OK" || echo "FAIL"
}

stop() {
    echo "Stopping tslib uinput interface..."
    if [ ! -f "$PIDFILE" ]; then
        rm -f /dev/input/guppy
        echo "Not running"
        return 0
    fi
    start-stop-daemon -K -q -p $PIDFILE
    result=$?
    rm -f "$PIDFILE" /dev/input/guppy
    [ $result = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart|reload)
        restart
    ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
