"""Project-owned defaults layered on top of Typer-generated font metrics.

``font_metrics.json`` is generated by Typer and intentionally contains only
measured font data. Keep product font selection and glyph fallback policy here so it remains
easy to find and override without changing Typer.
"""


DEFAULT_FONT = "JetBrainsMono 12pt"

FONT_FALLBACKS = {
    "Roboto 8pt": "JetBrainsMono 8pt",
    "Roboto 12pt": "JetBrainsMono 12pt",
    "Roboto 16pt": "JetBrainsMono 16pt",
    "Roboto 20pt": "JetBrainsMono 20pt",
    "Roboto 28pt": "JetBrainsMono 28pt",
    "Roboto Bold 8pt": "JetBrainsMono Bold 8pt",
    "Roboto Bold 12pt": "JetBrainsMono Bold 12pt",
    "Roboto Bold 16pt": "JetBrainsMono Bold 16pt",
    "Roboto Bold 20pt": "JetBrainsMono Bold 20pt",
    "Roboto Bold 28pt": "JetBrainsMono Bold 28pt",
}

# TODO: Move these values into a separately overridable Typer policy contract
# once Typer can provide it without turning generated metric data into a
# manually maintained configuration file.
