#!/bin/bash

## Service for forge-x camera
##
## Copyright (C) 2025-2026, Alexander K <https://github.com/drA1ex>
## Copyright (C) 2025, Sergei Rozhkov <https://github.com/ghzserg>
##
## This file may be distributed under the terms of the GNU GPLv3 license


if [ -f /tmp/SKIP_MOD ] || [ -f /tmp/SKIP_MOD_SOFT ] || [ -f /tmp/SKIP_MOD_HARD ]; then
    echo "Custom camera disabled due to SKIP_MOD mode"
    exit 0
fi

source /opt/config/mod/.shell/common.sh
CFG_PATH="/opt/config/mod_data/camera.conf"

# Create default configuration if needed
if [ ! -f "$CFG_PATH" ]; then
    cp "/opt/config/mod/.cfg/default/camera.conf" "$CFG_PATH"
fi


VIDEO="video0"

PID_FILE=/run/camera.pid
source "/opt/config/mod_data/camera.conf"

_STREAMER_DEVICE="/dev/${VIDEO}"

_FRAME_CAP_ARGS=()
if [ -z "$REDUCE_MEMORY" ] || [ "$REDUCE_MEMORY" == "1" ]; then
    _FRAME_CAP_ARGS=(--frame-cap)
fi

if [ "$VIDEO" = "auto" ]; then
    _STREAMER_DEVICE="auto"
fi

[[ " $* " =~ " --silent " ]] && SILENT=1 || SILENT=0

start() {
    echo "Starting camera..."

    enabled=$($CFG_SCRIPT "$VAR_PATH" --get "camera" "0")
    if [ "$enabled" -eq 1 ]; then
        start-stop-daemon -Sbm -p "$PID_FILE" --exec $BINS/mjpg_streamer -- \
            --device "${_STREAMER_DEVICE}" \
            --controls-file "$CFG_PATH" \
            --resolution "${WIDTH}x${HEIGHT}" \
            --fps "$FPS" \
            --buffers 1 \
            --listen 0.0.0.0 \
            --port 8080 \
            "${_FRAME_CAP_ARGS[@]}"
        
        touch "$CAMERA_F"
        echo "OK"

    else
        [ "$SILENT" -eq 0 ] && echo "Camera disabled in configuration"
    fi
}

stop() {
    echo "Stopping camera..."
    start-stop-daemon -K -p $PID_FILE > /dev/null 2>&1
    rm -f "$CAMERA_F"
    echo "OK"
}

restart() {
    if [ -f $PID_FILE ] && kill -0 "$(cat $PID_FILE)" 2> /dev/null; then
        stop
        sleep 2
    fi

    start
}

reload() {
    local enabled=$($CFG_SCRIPT "$VAR_PATH" --get "camera" "0")

    if [ "$enabled" -eq "0" ]; then
        if [ "$SILENT" -eq 0 ]; then
            echo "Camera disabled in configuration."
            echo "To enable the camera, run: SET_MOD PARAM='camera' VALUE=1"
            echo "A detailed guide can be found here: https://github.com/DrA1ex/ff5m/blob/main/docs/CAMERA.md"
        fi

        exit 1
    fi

    if ! [ -f $PID_FILE ] || ! kill -0 "$(cat $PID_FILE)" 2>/dev/null; then
        restart
        exit 0
    fi

    if ! kill -HUP "$(cat "$PID_FILE")"; then
        echo "Failed to request camera effects reload" >&2
        return 1
    fi

    [ "$SILENT" -eq 0 ] && echo "Effects applied"
}


case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    reload)
        reload "$2"
    ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
